# API Data structure and validation

from pydantic import BaseModel,ConfigDict,EmailStr  # importing basemodel class from pydantic library
from typing import Optional       # importing optional class from typing module
from datetime import datetime     # importing datetime class from datetime module

class CategoryCreate(BaseModel):  # Creating schema class to validate category table data that inherit from basemodel
    name : str   
class ProductCreate(BaseModel):  # creating schema class to validate product data that inherits from basemodel
    name : str  
    price : float
    description : Optional[str] = None
    category_id : int


class CategoryResponse(BaseModel):  # Pydantic schema that defines the structure of category data returned by the API
    id : int           # Product ID generated by the database and included in the API response
    name : str

    # Allows Pydantic to read data from SQLAlchemy model object attributes
    # such as student.id, student.name, student.age, etc.
    # model_config = ConfigDict(from_attributes=True)
    model_config = {
        "from_attributes" : True
    }


class ProductResponse(BaseModel): # Pydantic schema that defines the structure of product data returned by the API
    id : int        # Product ID generated by the database and included in the API response
    name : str      # Product name returned by the API
    price : float   # Product price returned by the API
    description : str # Product description returned by the API
    category_id : int # ID of the category to which this product belongs

    # Allows Pydantic to create the response model by reading attributes from SQLAlchemy objects
    model_config = ConfigDict(from_attributes=True)  


class ProductUpdate(BaseModel): # Defines the Pydantic schema used when updating a product
    name : str | None = None  # Allows the product name to be updated optionally
    price : float | None = None # Allows the product price to be updated optionally
    description : str | None = None # Allows the product description to be updated optionally
    category_id : int | None = None # Allows the product category ID to be updated optionally


class CategoryUpdate(BaseModel):  # Defines the Pydantic schema used when updating a category
    name : str | None = None  # Allows the category name to be updated optionally


class UserCreate(BaseModel):    # Schema for creating a new user
    username: str     # Username provided during user registration
    email : EmailStr  # Email address provided during user registration
    password : str    # Password provided during user registration

class UserResponse(BaseModel):     # Schema for returning user details in API responses
    id : int                       # Unique ID assigned by the database
    username : str                 # Username returned in the API response
    email : EmailStr               # Email address returned in the API response
    is_active : bool               # Indicates whether the user account is active
    role: str                      # Store the user's role (admin or user).
    created_at : datetime          # Date and time when the user account was created
    model_config = ConfigDict(from_attributes = True)   # Allow Pydantic to create this schema from SQLAlchemy model objects


class Token(BaseModel):           # Pydantic model for the JWT token returned after successful login.
    access_token: str             # Store the JWT access token returned after successful authentication.
    token_type : str              # Store the type of authentication token (usually "bearer").


class TokenData(BaseModel):   # Pydantic model for storing and validating decoded JWT token data.
    email: str | None = None  # Store the user's email extracted from the decoded JWT token.